---
- name: Basic Web Server Setup
  hosts: servers
  gather_facts: False
  become: yes
  tasks:
    - name: Ensure SSH connection is available
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ ansible_host | default(inventory_hostname) }}'
      vars:
        ansible_connection: local
      become: no

- name: Install Docker and Docker-compose
  hosts: servers
  become: yes
  vars_files:
    - ansible-vars.yaml
  tasks:
    - name: Update apt cache manually
      apt:
        update_cache: yes
        cache_valid_time: "{{ cache_time }}"

    - name: Install Docker
      apt:
        name: "{{ docker_package_name }}"
        update_cache: yes
        state: present

    - name: Install Docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker service is started
      systemd:
        name: "{{ docker_service_name }}"
        state: started
        enabled: yes

    - name: Check Docker version
      command: docker --version
      register: docker_version_output

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version_output.stdout }}"

    - name: Check Docker Compose version
      command: docker-compose --version
      register: docker_compose_version_output

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version_output.stdout }}"

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reconnect to server session
      meta: reset_connection

