- name: Create superuser inside backend container
  hosts: servers
  become: yes
  vars_files:
    - ansible-vars.yaml
  tasks:
    - name: Create superuser inside backend container
      command: >
        docker exec {{ backend_container_name }} python manage.py shell -c
        "from django.contrib.auth import get_user_model;
        User = get_user_model();
        User.objects.filter(username='{{ superuser_username }}').exists() or
        User.objects.create_superuser('{{ superuser_username }}', '{{ superuser_email }}', '{{ superuser_password }}')"
